name: astro_calc
description: Astronomical calculations in Dart.
version: 0.1.0
homepage: https://github.com/BendixMa/astro_calc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: